{% set name = "hssm" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hssm-{{ version }}.tar.gz
  sha256: 5065fb49f54112ab5082bb5e87ea90b0ce47d509fc8268aee67ee63e68a08b44

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.12
    - poetry-core
    - pip
  run:
    - python >=3.10,<3.12
    - pymc >=5.14
    - arviz >=0.18.0
    - onnx >=1.16.0,<2.0.0
    - jax >=0.4.25,<0.5.0
    - ssm-simulators >=0.7.2,<0.8.0
    - huggingface_hub >=0.23.0,<0.24.0
    - onnxruntime >=1.15.0,<2.0.0
    - bambi >=0.13.0,<0.14.0
    - formulae >=0.5.0,<0.5.2
    - numpyro >=0.14.0,<0.15.0
    - seaborn >=0.13.0,<0.14.0
    - hddm-wfpt >=0.1.4,<0.2.0
test:
  imports:
    - hssm
  # Temporarily not doing pip check because jaxlib version on conda-forge lags behind jax version
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://lnccbrown.github.io/HSSM/
  summary: Bayesian inference for hierarchical sequential sampling models.
  dev_url: https://github.com/lnccbrown/HSSM/
  license: LicenseRef-Brown-University-2023
  license_file: LICENSE

extra:
  recipe-maintainers:
    - digicosmos86
    - AlexanderFengler
